include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
      implicit-casts: false

linter:
  rules:
    - cancel_subscriptions
    - always_declare_return_types
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_in_for_each
    - always_use_package_imports
