name: nurse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite_sqlcipher: ^2.1.0
  path: ^1.8.0
  provider: ^6.0.3
  flutter_archive: ^5.0.0
  flutter_dotenv: ^5.0.2
  flutter_mobx: ^2.0.5
  mobx: ^2.0.7
  syncfusion_flutter_xlsio: ^20.2.50-beta
  path_provider: ^2.0.11
  open_file: ^3.2.1
  share_plus: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/script_v4_0.sql
    - assets/images/
    - .env

  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular/Righteous-Regular.ttf
    
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
