name: CI for tests on Flutter
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DATABASE_NAME: 'db.db'
  DATABASE_PASSWORD: 'password123'

jobs:
  flutter-test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings
      - run: flutter test
